### ISSUE TITLE
[IDE] no template in project wizard

### ISSUE THREAD

**Issue by hgkang** [webida/webida-client#714] opened 2015-11-20 06:14 UTC
I don't see any template in Project Wizard

**Comment by hwshim** [comment] 2015-11-20 06:29
@hgkang
@gotchazipc 
@kyungmi 

I think it's because of the loading performance problem sir.
We are improving server's performance now.

* #126 Improve server performance
* #144 Cache & Node 4.2

webida.net has been finished yesterday.
webida.org will be done in the next week.

Thanks.

**Comment by kyungmi** [comment] 2015-11-20 12:03
@hgkang We recently did some kind of improvement on performance. Getting project template becomes more faster than before. Please check it out at webida.net page.

**Comment by kyungmi** [comment] 2015-11-24 10:36
@hgkang I cannot reproduce this problem any more. I'll close this issue.

**Closed by kyungmi** 2015-11-24 10:36 UTC
Labels: bug, must be resolved
