### ISSUE TITLE
Remain empty space in editor when view disappear.

### ISSUE THREAD

**Issue by leechwin** [webida/webida-client#304] opened 2015-07-27 15:41 UTC
1. Editor open
2. Hidden to bottom view
3. remain empty space in editor

![image](https://cloud.githubusercontent.com/assets/510924/8910252/a73e4b98-34c0-11e5-9670-dc35a81a8596.png)

**Comment by happibum** [comment] 2015-07-28 02:14
Duplicate of #301

**Closed by happibum** 2015-07-28 02:14 UTC
