### ISSUE TITLE
Pressing enter brings out css-smart errors

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#840] opened 2015-12-15 08:57 UTC
1. on webida.net
2. Open any js file
3. Press enter
4. shows following errors

![image](https://cloud.githubusercontent.com/assets/7447396/11806217/f24112bc-a354-11e5-8f46-d5a9c163e292.png)

**Comment by happibum** [comment] 2015-12-15 09:02
Duplicate of #828. 
We may close one of them.

**Closed** 2015-12-15 09:35 UTC
Labels: bug, duplicate
