### ISSUE TITLE
When Git Pull, Find in Files is run, IDE comes to unresponsiveness.(Chrome on Windows7 only)

### ISSUE THREAD

**Issue by yserlee** [webida/webida-client#854] opened 2015-12-21 04:42 UTC
When I use Git Pull or Find in Files, IDE always comes to unresponsiveness.
So I can't use these features.
I used Chrome browser.
And this bug did not occur in Firefox.

**Comment by kyungmi** [comment] 2015-12-23 09:54
Change the assignee becase @minsung-jin cannot reproduce this issues with his Chrome browser.

**Comment by kyungmi** [comment] 2015-12-28 08:16
It was fixed In all cases with PR #869

**Closed** 2015-12-28 08:16 UTC
Labels: bug, critical, in progress
